sudo: required

services:
  - docker

language: go
go:
  - 1.9

env:
  matrix:
    - OKARCH=amd64 OSARCH=amd64
    - OKARCH=386 OSARCH=i386
  global:
    - VERSION=${TRAVIS_TAG}
    - GH_USER=${TRAVIS_REPO_SLUG%/*}
    - GH_APP=${TRAVIS_REPO_SLUG#*/}
    - JFROG_CLI_OFFER_CONFIG=false
    # bintray token
    - secure: uUsxcTceYD5fMyCm1YaDbOwdDuAUn4MjX861d/EcwpVcuQcWdawewYwg8mAoy+0ast1nJBWZWaJfn3Rj0pBWRaZDmL3A69zs5VJMVOIxlRT4qYvBPaM4nkFBIRaHpY52Ahyzh9Gkfbsl9jWavYvI4LQKKDssygDfsbEu/P9FwYUl3ojCeyvenVjUoXeLZ7bHDPKEizQDfSiHlTerXOHbnv7E0s43awRHsFxPiH81Vv30isyQmkDWwrOQ8CQmIE7wrjooqZQYwbUVejn4h0wywdadN/tvrAjMOynL7cekGtcynqp8tLxY94XPW0jAZaZovwCnu6T2O4JRc9rzEEYMIDBy79P/WYcCTdxo/r61mua8eMOcZxsLdgPnky6dZYFGM5yiDlicJPYJZEAmz6OA+7WnkXfK0CjuX92iDHj5s/5mJivg1n6k2++91MYAmpc+5yIJiDiSumWddZg5UoovCeHK58+DYTDtfaovB7bEUcIWmr4xv5XcXZ8fRZX6CJJPayFcKfEtvNYthOL91/tGGUwjillMtM3OvC0aJb8vZtrXYavD/3Li2TirMLMN0+RDjg3DjCEMvLClfJLtM2aG2+ISFCcn6awsUx8ThwQlrLIKmzXXq+tnUNlcUcb7HhHUQD96WqSKuk38wvM3NS1OGR3ckCo/kfgouQMd+h3BcKE=

before_install:
  - sudo add-apt-repository 'deb https://dl.bintray.com/mh-cbon/deb unstable main'
  - sudo apt-get -qq update
  - sudo apt-get install --allow-unauthenticated changelog go-bin-deb fakeroot
  - mkdir -p ${GOPATH}/bin
  - cd ~
  - curl https://glide.sh/get | sh

install:
  - cd $GOPATH/src/github.com/$TRAVIS_REPO_SLUG
  - glide install
  - go install

script:
  - go test emd/*
  - sh test.sh

before_deploy:
  # create the deb package
  - cd $GOPATH/src/github.com/$TRAVIS_REPO_SLUG
  - mkdir -p build/$OSARCH
  - GOOS=linux go build --ldflags "-X main.VERSION=$VERSION" -o build/$OSARCH/$GH_APP main.go
  - go-bin-deb generate --file deb.json -a $OSARCH --version $VERSION -o $GH_APP-$OSARCH-$VERSION.deb
  # copy the deb for gh release (backward compatibility)
  - cp $GH_APP-$OSARCH-$VERSION.deb $GH_APP-$OKARCH.deb
  # upload to bintray
  - curl -fL https://getcli.jfrog.io | sh
  - ls -alh
  - ./jfrog bt pc --key=$BTKEY --user=$GH_USER --licenses=MIT --vcs-url=https://github.com/$GH_USER/deb $GH_USER/deb/$GH_APP || echo "package already exists"
  - ./jfrog bt upload --override=true --key $BTKEY --publish=true --deb=unstable/main/$OSARCH $GH_APP-$OSARCH-$VERSION.deb $GH_USER/deb/$GH_APP/$VERSION pool/g/$GH_APP/
  # prepare rpm package creation
  - docker pull fedora
  # create the package in the docker
  - >
    docker run -v $PWD:/mnt/travis fedora /bin/sh -c
    "cd /mnt/travis && (curl -s -L https://bintray.com/mh-cbon/rpm/rpm > /etc/yum.repos.d/w.repo) && dnf install go-bin-rpm changelog rpm-build -y --quiet && go-bin-rpm generate --file rpm.json -a $OSARCH --version $VERSION -o $GH_APP-$OSARCH-$VERSION.rpm"
  # copy the rpm for gh release (backward compatibility)
  - cp $GH_APP-$OSARCH-$VERSION.rpm $GH_APP-$OKARCH.rpm
  # upload to bintray
  - ./jfrog bt pc --key=$BTKEY --user=$GH_USER --licenses=MIT --vcs-url=https://github.com/$GH_USER/rpm $GH_USER/rpm/$GH_APP || echo "package already exists"
  - ./jfrog bt upload --override=true --key $BTKEY --publish=true $GH_APP-$OSARCH-$VERSION.rpm $GH_USER/rpm/$GH_APP/$VERSION pool/$POOL/$GH_APP/
  # generate the repo metadata
  - curl -X POST -u ${GH_USER}:${BTKEY} https://api.bintray.com/calc_metadata/${GH_USER}/rpm
  
deploy:
  provider: releases
  api_key:
    secure: em4nCHJdPAXZ+jP/uDflyFfELb9Yn5B3C7rqjBYm1SdTi1KZVZyyOohckoPmljoHt2kva1ls5yszp8pFCj8mFXi1kY6UVV77VC6tYmcrGmP9FXz2iY+X3q2wulu8bU7f+mcG/whfOKPVU/hxLm6iNfcUw3oWNvH8vdZodtBse5UwFi4VkWZBa08Oj9JRR2P0JSMyHsDbvTNeC25xz8j9ytHcv2+j7pvOQf+Swam3z/FknRkG5hxpklMiFCBxKo4FkMKmSNWaH7F2AXGwTyqBgCj4uOEAJsp2Gi27Gw+dC8OOKxx/t9e4l38i5QqWVGVuSFW+wOLwr2StT5rVVG+QDxv61nkh5vLsXckRe7zxA4D2ldf8KtkyLP4vNaAtbUFTmyRJ+I8LhicAn6j4vjOtYpB+CwkGI21if1GEU7fygF7fyIqBss9TOHb4OJUNK16ZVA0do+ZGDcwTgPx11zcgd2Emxl4z2I/ue7OXXJ1hz95tHqMZz8z0hKffdxmVOgp3pQ9w8VoZfBxicGRrWKnr35vH2vkx3R2mmLj7MW3DpDrCRD3qSQ2A7hu4vEiTY0c1yzy6OEWwgfJsx7hnRSU29iaw9Ep0ScXxf/2DtWA6DxY6A/sWd1jGePPlPhOTpx5fdLEiITR0DyHKpe5tHDfXJl6Jn0fwl8nwCc4+bGSAMqk=
  file_glob: true
  file:
    - $GH_APP-$OKARCH.deb
    - $GH_APP-$OKARCH.rpm
  skip_cleanup: true
  on:
    tags: true
